### PR TITLE
(#39) allow provisioned throughput in create-tables to be number or string

### PR DESCRIPTION
**Pull request by keithbranton**
Expect number values for these, permit quoted number for backward compatibility.

### CODE REVIEW

**Comment by keithbranton** [comment]
Not sure how I could have cause the CI error - looks like the version of hibernate validator being used was compiled with Java 7

**Comment by dmarkov** [comment]
@keithbranton Thanks, I will find someone to review this PR soon

**Comment by dmarkov** [comment]
@caarlos0 please review, thanks

**Comment by caarlos0** [comment]
@keithbranton looks good, thanks

**Comment by caarlos0** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge pls

**Comment by dmarkov** [comment]
@caarlos0 **17 mins** sent to your balance (ID `5668064a5cf241793b00019b`), many thanks! It took 168 hours and 21 mins.. you're getting extra minutes here (c=2). +17 to your rating, your total score is [+254](http://www.netbout.com/b/35095?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy now pls

**Pull request merged**
