### PR TITLE
upgrade to jcabi 1.24

### PR DESCRIPTION
**Pull request by simonjenga**
Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by simonjenga** [comment]
This PR is for issue #73

**Comment by 0crat** [comment]
@simonjenga[/z](https://www.0crat.com/u/simonjenga) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@rultor merge

**Comment by simonjenga** [comment]
@yegor256 What version of `JDK `does @rultor use?

Am using `JDK 8` and when I upgrade to jcabi `1.25.1` I get the following compilation error:
```
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ jcabi-dynamodb-maven-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 10 source files to C:\javaworkspace\jcabi-dynamodb-maven-plugin\target\classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING :
[INFO] -------------------------------------------------------------
[WARNING] Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.8'
[INFO] 1 warning
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] warnings found and -Werror specified
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by 0crat** [comment]
Job `gh:jcabi/jcabi-dynamodb-maven-plugin#75` is not assigned, can't get performer

**Pull request closed without merging**
