### PR TITLE
#55 Making AbstractDynamoMojo#environment method abstract

### PR DESCRIPTION
**Pull request by prondzyn**
This is for #55.

Method `AbstractDynamoMojo#environment()` made abstract and necessary implementations provided.

### CODE REVIEW

**Comment by dmarkov** [comment]
@prondzyn Thanks, let me find someone who can review this pull request

**Comment by dmarkov** [comment]
@pinaf please review this PR

**Comment by pinaf** [comment]
@rultor merge

**Comment by prondzyn** [comment]
@yegor256 ping

**Comment by prondzyn** [comment]
@yegor256 please confirm this.

**Comment by yegor256** [comment]
@rultor merge

**Comment by dmarkov** [comment]
@pinaf Thanks a lot, I just topped your account for **16 mins**, transaction ID `57cffa7adacf4d0c7b062151`, total time was 186 hours and 55 mins. extra minutes for review comments (c=1). added +16 to your rating, now it is equal to [+308](http://www.netbout.com/b/35128?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
