### PR TITLE
Upgrade to 1.11.25 aws-java-sdk-core and aws-java-sdk-dynamodb

### PR DESCRIPTION
**Pull request by loic-seguin**
Linked to issue #63.

Thanks

### CODE REVIEW

**Comment by dmarkov** [comment]
@loic-seguin I will find a reviewer for your pull requests shortly, thanks for contribution!

**Comment by dmarkov** [comment]
@yegor256 review it please, it is a rather short pull request, no need to do a full code review

**Comment by yegor256** [comment]
@rultor try to merge

**Comment by yegor256** [comment]
@loic-seguin thanks!

**Comment by dmarkov** [comment]
@yegor256 **17 mins** sent to your balance (ID `000-b0f27497`), many thanks! It took 884 hours and 45 mins.

you're getting extra minutes here (c=2)

+17 added to your rating, at the moment it is: [+85](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
