### PR TITLE
modified .gitignore with more files

### PR DESCRIPTION
**Pull request by simonjenga**
modified .gitignore with more files

### CODE REVIEW

**Comment by dmarkov** [comment]
@simonjenga Many thanks for the PR, let me find a reviewer for it

**Comment by dmarkov** [comment]
@yegor256 the PR is rather short, please review it

**Comment by yegor256** [comment]
@rultor merge it

**Comment by dmarkov** [comment]
@yegor256 Thanks for your contribution, **16 mins** was added to your account, payment ID is `000-6e0ad22c`, 3 hours and 53 mins spent total; you're getting extra minutes here (c=1); +16 added to your rating, current score is: [+7778](http://www.netbout.com/b/35008?open=rating)

**Comment by dmarkov** [comment]
@rultor deploy

**Pull request merged**
